# Generated by Django 4.0.1 on 2022-01-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusapi', '0002_album_mimetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='mimetype',
        ),
        migrations.AddField(
            model_name='photo',
            name='mimetype',
            field=models.CharField(default='application/octet-stream', max_length=512),
        ),
    ]
