# Generated by Django 4.0.1 on 2022-01-16 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('focusapi', '0003_remove_album_mimetype_photo_mimetype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('name', 'created_by')},
        ),
    ]
