SUCCESS_CODE = 0
SUCCESS_MESSAGE = "Successful"
MISSING_PARAMETER_CODE = 1
MISSING_PARAMETER_MESSAGE = "Parameter missing or invalid"
INVALID_LOGIN_CREDENTIALS_CODE = 2
INVALID_LOGIN_CREDENTIALS_MESSAGE = "Invalid login credentials"
